# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Tue Dec 11 09:00:50 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1174, 663)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Downloads/1355009308_Gnome-Face-Monkey-64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget_2 = QtGui.QTabWidget(self.frame)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(175, 16777215))
        self.tabWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.peersView = QtGui.QListWidget(self.tab_3)
        self.peersView.setFrameShape(QtGui.QFrame.NoFrame)
        self.peersView.setObjectName(_fromUtf8("peersView"))
        self.verticalLayout_4.addWidget(self.peersView)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget_2)
        self.widget = QtGui.QWidget(self.frame)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget_3 = QtGui.QTabWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_9)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.filesView = QtGui.QTableWidget(self.tab_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesView.sizePolicy().hasHeightForWidth())
        self.filesView.setSizePolicy(sizePolicy)
        self.filesView.setFrameShape(QtGui.QFrame.Box)
        self.filesView.setAlternatingRowColors(True)
        self.filesView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.filesView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.filesView.setShowGrid(True)
        self.filesView.setGridStyle(QtCore.Qt.SolidLine)
        self.filesView.setWordWrap(True)
        self.filesView.setColumnCount(3)
        self.filesView.setObjectName(_fromUtf8("filesView"))
        self.filesView.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.filesView.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filesView.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.filesView.setHorizontalHeaderItem(2, item)
        self.filesView.horizontalHeader().setVisible(True)
        self.filesView.horizontalHeader().setCascadingSectionResizes(True)
        self.filesView.horizontalHeader().setHighlightSections(True)
        self.filesView.horizontalHeader().setSortIndicatorShown(True)
        self.filesView.horizontalHeader().setStretchLastSection(True)
        self.filesView.verticalHeader().setVisible(True)
        self.filesView.verticalHeader().setHighlightSections(True)
        self.filesView.verticalHeader().setSortIndicatorShown(False)
        self.filesView.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.filesView)
        self.downloadButton = QtGui.QPushButton(self.tab_9)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.verticalLayout_6.addWidget(self.downloadButton)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout = QtGui.QFormLayout(self.frame_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(30, -1, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.searchInput = QtGui.QLineEdit(self.frame_5)
        self.searchInput.setObjectName(_fromUtf8("searchInput"))
        self.horizontalLayout_3.addWidget(self.searchInput)
        self.searchButton = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.horizontalLayout_3.addWidget(self.searchButton)
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.frame_5)
        self.label_4 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.searchResultsView = QtGui.QListWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.searchResultsView.sizePolicy().hasHeightForWidth())
        self.searchResultsView.setSizePolicy(sizePolicy)
        self.searchResultsView.setObjectName(_fromUtf8("searchResultsView"))
        self.verticalLayout_2.addWidget(self.searchResultsView)
        self.downloadSearchButton = QtGui.QPushButton(self.frame_2)
        self.downloadSearchButton.setObjectName(_fromUtf8("downloadSearchButton"))
        self.verticalLayout_2.addWidget(self.downloadSearchButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget_3.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget_3)
        self.horizontalLayout.addWidget(self.widget)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/monkeyshare/1355009308_Gnome-Face-Monkey-64.png")))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1174, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPeers = QtGui.QMenu(self.menubar)
        self.menuPeers.setObjectName(_fromUtf8("menuPeers"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.NoToolBarArea)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAdd_Peer = QtGui.QAction(MainWindow)
        self.actionAdd_Peer.setObjectName(_fromUtf8("actionAdd_Peer"))
        self.actionRemove_Peer = QtGui.QAction(MainWindow)
        self.actionRemove_Peer.setObjectName(_fromUtf8("actionRemove_Peer"))
        self.actionRefresh_Peers = QtGui.QAction(MainWindow)
        self.actionRefresh_Peers.setObjectName(_fromUtf8("actionRefresh_Peers"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAdd_Peer_2 = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/monkeyshare/onebit_31.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Peer_2.setIcon(icon1)
        self.actionAdd_Peer_2.setObjectName(_fromUtf8("actionAdd_Peer_2"))
        self.actionRemove_Peer_2 = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/monkeyshare/onebit_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Peer_2.setIcon(icon2)
        self.actionRemove_Peer_2.setObjectName(_fromUtf8("actionRemove_Peer_2"))
        self.actionRefresh_Peers_2 = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/monkeyshare/1355012772_arrow_cycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh_Peers_2.setIcon(icon3)
        self.actionRefresh_Peers_2.setObjectName(_fromUtf8("actionRefresh_Peers_2"))
        self.actionSettings_2 = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/monkeyshare/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings_2.setIcon(icon4)
        self.actionSettings_2.setObjectName(_fromUtf8("actionSettings_2"))
        self.actionAbout_2 = QtGui.QAction(MainWindow)
        self.actionAbout_2.setObjectName(_fromUtf8("actionAbout_2"))
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuPeers.addAction(self.actionAdd_Peer)
        self.menuPeers.addAction(self.actionRemove_Peer)
        self.menuPeers.addAction(self.actionRefresh_Peers)
        self.menuHelp.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPeers.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAdd_Peer_2)
        self.toolBar.addAction(self.actionRemove_Peer_2)
        self.toolBar.addAction(self.actionRefresh_Peers_2)
        self.toolBar.addAction(self.actionSettings_2)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Monkey Share", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Online Peers", None, QtGui.QApplication.UnicodeUTF8))
        self.filesView.setSortingEnabled(True)
        item = self.filesView.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.filesView.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.filesView.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Checksum", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("MainWindow", "Download Selected FIle", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "File Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Search for files:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Search Terms:", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Download Selected File", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPeers.setTitle(QtGui.QApplication.translate("MainWindow", "Peers", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Peer.setText(QtGui.QApplication.translate("MainWindow", "Add Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Peer.setText(QtGui.QApplication.translate("MainWindow", "Remove Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_Peers.setText(QtGui.QApplication.translate("MainWindow", "Refresh Peers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Peer_2.setText(QtGui.QApplication.translate("MainWindow", "Add Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Peer_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a new peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Peer_2.setText(QtGui.QApplication.translate("MainWindow", "Remove Peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Peer_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove an existing peer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_Peers_2.setText(QtGui.QApplication.translate("MainWindow", "Refresh Peers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_Peers_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh all peers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings_2.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit the settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_2.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
